### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by monutb91** [map-os/mapos#190]
** Descreva o bug **
Durante instalação, ao rodar **php artisan key:generate apresentou ErrorExpection.**
Rodei o server e a mensagem "**500 | Server Erro**" aparece no http://localhost:8000/.

** Capturas de tela **
![image](https://user-images.githubusercontent.com/68172360/115968358-fea02c80-a50d-11eb-8ed7-58cc7de59ca5.png)

** Desktop (preencha as seguintes informações): **
 - SO: Windows 10
 - Navegador Chrome/FireFox

**Comment by monutb91** [comment]
Então, instalação foi resolvida. O erro agora é na conexão com o bando de dados. Não localizo o arquivo para inserir os dados do banco (usuario, password, dbname). Qual o caminho?
Instalado em C:\mapos

**Comment by monutb91** [comment]
Desculpa ai, to aprendendo laravel agora ^^"
dados para conexão nos arquvios .env correto?
Alterei de acordo com meus server (xampp) mas ainda apresenta erro 500. 

Alguem saberia ajudar?

**Comment by Pr3d4dor** [comment]
Boa tarde @monutb91 o mapos laravel ainda não está em um estado usável, ainda falta terminar várias coisas.

Sobre o erro, se puder compartilhar mais detalhes, ficaria mais fácil de tentar lhe ajudar.
