### ISSUE TITLE
Bug no ato de atualização 

### ISSUE THREAD

**Issue by willybrandtleao** [map-os/mapos#243]
Olá a todas e todos

Fui tentar atualizar via sistema e me apareceu esse erro, será que alguem conseguiria me ajudar?

![124018742-8c8d0d80-d9be-11eb-8e3b-050c729dceb0](https://user-images.githubusercontent.com/46223150/126305469-58a6fde9-fa42-4d50-89f9-2f6cc61bf517.png)
![124018816-a595be80-d9be-11eb-8b03-a6fe68aa3785](https://user-images.githubusercontent.com/46223150/126305473-d794e478-dda1-4485-af21-150d383f5af6.png)
![124018899-bfcf9c80-d9be-11eb-9b9c-85bcf01b0845](https://user-images.githubusercontent.com/46223150/126305478-163523e8-a490-40e5-ac25-653174bc0c94.png)
![124018926-c9590480-d9be-11eb-931b-12eb4fc626a0](https://user-images.githubusercontent.com/46223150/126305479-5721300e-20b1-449a-9b5e-87adb9d5afc8.png)
![124018953-d0801280-d9be-11eb-9d96-095d413f51ab](https://user-images.githubusercontent.com/46223150/126305480-bd60ddf7-7e0d-41fe-baef-76090567eb4c.png)
![124018979-da097a80-d9be-11eb-920a-4b6281a082df](https://user-images.githubusercontent.com/46223150/126305482-16d6c90b-b081-4fa4-bfc9-3c11c758b2d2.png)

**Comment by Pr3d4dor** [comment]
Recomendo atualizar manualmente pois o atualizado apresenta alguns bugs.
