### ISSUE TITLE
 500 | Server Error

### ISSUE THREAD

**Issue by monutb91** [map-os/mapos#279]
Boa tarde pessoal!
Utilizo o Mapos a um certo tempo, em PHP. Resolvi instalar este em Laravel.

A mensagem de erro "500 | Server Error" me é mostrada. 
Arquivo ".env.production" esta com as informações do DB. 

Alguem tem uma dica do que posso estar fazendo errado?

**Comment by Pr3d4dor** [comment]
@monutb91 o mapos em laravel ainda está nos estágios iniciais e não está pronto para uso, recomendo usar por enquanto ainda o mapos antigo.

**Comment by PiahDoNeumann** [comment]
Conseguiu resolver? Aqui fiz a instalação hoje (23/09) e segui os passos que estão na página inicial:
Crie o arquivo de configuração de variáveis de ambiente cp .env.production .env
Configure as variáveis de ambiente e a conexão com o banco de dados no arquivo .env
Rode os seeders php artisan migrate:fresh --seed
Rode php artisan key:generate

e realizei a configuração no arquivo .env.

Deu erro, pq no restart do Laragon, parou tudo. Reiniciei a máquina e tudo voltou a normalidade. 

Excelente dia!!

**Comment by anisotton** [comment]
Bom dia, 

Tive exatamente o mesmo problema, corrigi limpando o cache através do comando: php artisan config:cache

Abçs

**Comment by Pr3d4dor** [comment]
@PiahDoNeumann @anisotton O projeto ainda está no início com apenas algumas funcionalidades porém ainda creio que não possa ser usado pois ainda falta a principal parte que é de OS.
