### ISSUE TITLE
4 ANOS....

### ISSUE THREAD

**Issue by armandinhox** [map-os/mapos#488]
Existe alguma chance da migração pro laravel? Existe alguém trabalhando ainda?

**Comment by armandinhox** [comment]
Existe algo sobre o projeto ainda? tem interesse em vender toda a base para continuação com código fechado? So que no caso deveria falar com o outro rapaz o que fez o original naquele outro framework ne?

**Comment by Pr3d4dor** [comment]
Está sendo desenvoldo, não temos interesse em vender pois o código será público e open-source. Eu e o @willph somos os mantenedores oficiais do mapos atualmente. O Ramon nos deu permissão total para conduzirmos o projeto.

Se quer contribuir, o que você pode fazer é doação para o projeto original.
