### ISSUE TITLE
Anexos vinculados ao Cadastro do Cliente

### ISSUE THREAD

**Issue by joubertdias** [map-os/mapos#66]
Olá desde já saúde a todos os teus! Utilizo o map-os para controle de serviço e gostaria de implementar os anexos também para o cadastro de clientes pois muitos tem contratos sociais e outros documentos que são necessários na presatação de serviços não somente na área que atuo mas também em outros segmentos, acredito que esta implementação pode ajudar e contribuir no sistema para muitos outros usuários.
Eu futrico bastante tenho como hobie a programação e desenvolvimento, claro que em nível intermediário para baixo bas já me defendo bastante, dei uma mexida no sistema para ajustar a minha realidade, mas estou em dificuldade nesta "simples" tarefa, portanto a dúvida é a que segue: Seria mais fácil criar outra tabela tipo Anexo_cliente e id_os vincular ao idAnexos o idClientes e copiar a estrutura dos anexos lá para o Editar_cliente? ou Criar na tabela do Cliente os campos necessários para anexar arquivos? 
Acredito que em ambas situações teria que criar uma nova rotina na controller e na models ou não?
 Desde já obrigado pela atenção.

**Comment by Pr3d4dor** [comment]
@joubertdias Tem como você criar a issue no outro repositório?

Esse repositório é do mapos que está sendo refeito em Laravel.

**Comment by joubertdias** [comment]
> @joubertdias Tem como você criar a issue no outro repositório?
> 
> Esse repositório é do mapos que está sendo refeito em Laravel.

No caso o do Ramon?

**Comment by Pr3d4dor** [comment]
@joubertdias Sim, do Ramon
